import assert from "node:assert/strict";
import test from "node:test";

import {
  buildCodeToDesignPlan,
  type CodeToDesignLayoutNode,
  parseCssColor,
  parseCssFontFamilies,
  parseSimpleLinearGradient,
} from "./code-to-design-plan.js";
import { buildCodeToDesignRuntimeSnapshot } from "./code-to-design-snapshot.js";

function findNodeById(root: CodeToDesignLayoutNode, nodeId: string): CodeToDesignLayoutNode | null {
  const stack = [root];
  while (stack.length) {
    const node = stack.pop()!;
    if (node.id === nodeId) {
      return node;
    }
    stack.push(...[...node.children].reverse());
  }
  return null;
}

test("parseCssColor supports rgba and opaque hex values", () => {
  assert.deepEqual(parseCssColor("rgba(15, 15, 15, 0.72)"), {
    hex: "#0F0F0F",
    opacity: 0.72,
  });
  assert.deepEqual(parseCssColor("#AABBCC"), {
    hex: "#AABBCC",
    opacity: 1,
  });
  assert.equal(parseCssColor("transparent"), null);
});

test("parseSimpleLinearGradient supports simple degree-based gradients", () => {
  const gradient = parseSimpleLinearGradient("linear-gradient(180deg, rgb(250, 248, 243) 0%, rgb(240, 235, 228) 100%)");
  assert.equal(gradient?.angle, 180);
  assert.equal(gradient?.stops.length, 2);
  assert.equal(gradient?.stops[0]?.color.hex, "#FAF8F3");
});

test("parseSimpleLinearGradient supports computed gradients without explicit angle or stop offsets", () => {
  const gradient = parseSimpleLinearGradient("linear-gradient(rgb(250, 248, 243), rgb(240, 235, 228))");
  assert.equal(gradient?.angle, 180);
  assert.deepEqual(
    gradient?.stops.map((stop) => ({ hex: stop.color.hex, offset: stop.offset })),
    [
      { hex: "#FAF8F3", offset: 0 },
      { hex: "#F0EBE4", offset: 1 },
    ],
  );
});

test("parseCssFontFamilies preserves CSS fallback order", () => {
  assert.deepEqual(parseCssFontFamilies(`"Iowan Old Style", "Times New Roman", serif`), [
    "Iowan Old Style",
    "Times New Roman",
    "serif",
  ]);
});

test("buildCodeToDesignPlan creates root, background, text and image commands", () => {
  const snapshot = buildCodeToDesignRuntimeSnapshot({
    projectRoot: "/tmp/aitest",
    projectName: "aitest",
    route: "/",
    entryPaths: ["src/App.tsx"],
    viewport: {
      width: 1440,
      height: 2200,
      deviceScaleFactor: 1,
    },
    page: {
      title: "AItest",
      urlPath: "/",
      scrollWidth: 1440,
      scrollHeight: 2200,
      backgroundColor: "rgb(245, 242, 236)",
      backgroundImage: "linear-gradient(180deg, rgb(250, 248, 243) 0%, rgb(240, 235, 228) 100%)",
    },
    nodes: [
      {
        id: "text-1",
        parentId: "root-1",
        domPath: "body>div>h1",
        tagName: "H1",
        role: "text",
        name: "Headline",
        visible: true,
        rect: { x: 60, y: 80, width: 520, height: 180 },
        textContent: "SHADOW OF ELEGANCE",
        styles: {
          display: "block",
          position: "static",
          color: "rgb(15, 15, 15)",
          opacity: 1,
          backgroundColor: "rgba(0, 0, 0, 0)",
          backgroundImage: "none",
          borderTopWidth: "0px",
          borderRightWidth: "0px",
          borderBottomWidth: "0px",
          borderLeftWidth: "0px",
          borderTopColor: "rgba(0, 0, 0, 0)",
          borderRightColor: "rgba(0, 0, 0, 0)",
          borderBottomColor: "rgba(0, 0, 0, 0)",
          borderLeftColor: "rgba(0, 0, 0, 0)",
          borderTopLeftRadius: "0px",
          borderTopRightRadius: "0px",
          borderBottomRightRadius: "0px",
          borderBottomLeftRadius: "0px",
          fontFamily: "Didot",
          fontSize: "80px",
          fontWeight: "600",
          lineHeight: "84px",
          letterSpacing: "-4px",
          textAlign: "left",
          textTransform: "uppercase",
          objectFit: "fill",
          gridTemplateColumns: "none",
          gridTemplateRows: "none",
          gap: "normal",
          rowGap: "normal",
          columnGap: "normal",
        },
        image: null,
      },
      {
        id: "image-1",
        parentId: "root-1",
        domPath: "body>div>figure>img",
        tagName: "IMG",
        role: "image",
        name: "Hero Image",
        visible: true,
        rect: { x: 700, y: 100, width: 480, height: 680 },
        textContent: null,
        styles: {
          display: "block",
          position: "static",
          color: "rgb(0, 0, 0)",
          opacity: 1,
          backgroundColor: "rgba(0, 0, 0, 0)",
          backgroundImage: "none",
          borderTopWidth: "0px",
          borderRightWidth: "0px",
          borderBottomWidth: "0px",
          borderLeftWidth: "0px",
          borderTopColor: "rgba(0, 0, 0, 0)",
          borderRightColor: "rgba(0, 0, 0, 0)",
          borderBottomColor: "rgba(0, 0, 0, 0)",
          borderLeftColor: "rgba(0, 0, 0, 0)",
          borderTopLeftRadius: "0px",
          borderTopRightRadius: "0px",
          borderBottomRightRadius: "0px",
          borderBottomLeftRadius: "0px",
          fontFamily: "Helvetica Neue",
          fontSize: "16px",
          fontWeight: "400",
          lineHeight: "normal",
          letterSpacing: "normal",
          textAlign: "left",
          textTransform: "none",
          objectFit: "cover",
          gridTemplateColumns: "none",
          gridTemplateRows: "none",
          gap: "normal",
          rowGap: "normal",
          columnGap: "normal",
        },
        image: {
          src: "/editorial/fashion-7.jpg",
          alt: "Hero",
          dataUrl: "data:image/png;base64,AAAA",
        },
      },
    ],
  });

  const plan = buildCodeToDesignPlan({
    snapshot,
    frameName: "AItest Page",
    parentNodeId: "1:2",
  });

  assert.equal(plan.summary.commandCount, 4);
  assert.equal(plan.summary.textCommandCount, 1);
  assert.equal(plan.summary.imageCommandCount, 1);
  assert.equal(plan.batch.commands[0].type, "capability");
  assert.equal((plan.batch.commands[0] as { capabilityId: string }).capabilityId, "nodes.create-frame");
  assert.equal((plan.batch.commands[1] as { capabilityId: string }).capabilityId, "nodes.create-svg");
  assert.equal((plan.batch.commands[2] as { capabilityId: string }).capabilityId, "nodes.create-text");
  assert.equal((plan.batch.commands[3] as { capabilityId: string }).capabilityId, "nodes.create-image");
  assert.equal(
    (plan.batch.commands[2] as { payload: { textAutoResize?: string } }).payload.textAutoResize,
    "HEIGHT",
  );
  assert.deepEqual(
    (plan.batch.commands[2] as { payload: { fontFamilyCandidates?: string[] } }).payload.fontFamilyCandidates,
    ["Didot"],
  );
});

test("buildCodeToDesignPlan can fallback image nodes to frame+raster reconstruction", () => {
  const snapshot = buildCodeToDesignRuntimeSnapshot({
    projectRoot: "/tmp/aitest",
    projectName: "aitest",
    route: "/",
    entryPaths: ["src/App.tsx"],
    viewport: {
      width: 1440,
      height: 2200,
      deviceScaleFactor: 1,
    },
    page: {
      title: "AItest",
      urlPath: "/",
      scrollWidth: 1440,
      scrollHeight: 2200,
      backgroundColor: "rgb(245, 242, 236)",
      backgroundImage: "linear-gradient(180deg, rgb(250, 248, 243) 0%, rgb(240, 235, 228) 100%)",
    },
    nodes: [
      {
        id: "image-1",
        parentId: "root-1",
        domPath: "body>div>figure>img",
        tagName: "IMG",
        role: "image",
        name: "Hero Image",
        visible: true,
        rect: { x: 700, y: 100, width: 480, height: 680 },
        textContent: null,
        styles: {
          display: "block",
          position: "static",
          color: "rgb(0, 0, 0)",
          opacity: 1,
          backgroundColor: "rgba(0, 0, 0, 0)",
          backgroundImage: "none",
          borderTopWidth: "0px",
          borderRightWidth: "0px",
          borderBottomWidth: "0px",
          borderLeftWidth: "0px",
          borderTopColor: "rgba(0, 0, 0, 0)",
          borderRightColor: "rgba(0, 0, 0, 0)",
          borderBottomColor: "rgba(0, 0, 0, 0)",
          borderLeftColor: "rgba(0, 0, 0, 0)",
          borderTopLeftRadius: "12px",
          borderTopRightRadius: "12px",
          borderBottomRightRadius: "12px",
          borderBottomLeftRadius: "12px",
          fontFamily: "Helvetica Neue",
          fontSize: "16px",
          fontWeight: "400",
          lineHeight: "normal",
          letterSpacing: "normal",
          textAlign: "left",
          textTransform: "none",
          objectFit: "cover",
          gridTemplateColumns: "none",
          gridTemplateRows: "none",
          gap: "normal",
          rowGap: "normal",
          columnGap: "normal",
        },
        image: {
          src: "/editorial/fashion-7.jpg",
          alt: "Hero",
          dataUrl: "data:image/png;base64,AAAA",
        },
      },
    ],
  });

  const plan = buildCodeToDesignPlan({
    snapshot,
    parentNodeId: "1:2",
    imageStrategy: "frame_raster",
  });

  assert.equal(plan.summary.commandCount, 5);
  assert.equal(plan.summary.imageCommandCount, 1);
  assert.equal((plan.batch.commands[2] as { capabilityId: string }).capabilityId, "nodes.create-frame");
  assert.equal((plan.batch.commands[3] as { capabilityId: string }).capabilityId, "nodes.set-clips-content");
  assert.equal((plan.batch.commands[4] as { capabilityId: string }).capabilityId, "reconstruction.apply-raster-reference");
});

test("buildCodeToDesignPlan rejects text raster overrides so non-image content stays editable", () => {
  const snapshot = buildCodeToDesignRuntimeSnapshot({
    projectRoot: "/tmp/aitest",
    projectName: "aitest",
    route: "/",
    entryPaths: ["src/App.tsx"],
    viewport: {
      width: 1440,
      height: 2200,
      deviceScaleFactor: 1,
    },
    page: {
      title: "AItest",
      urlPath: "/",
      scrollWidth: 1440,
      scrollHeight: 2200,
      backgroundColor: "transparent",
      backgroundImage: "none",
    },
    nodes: [
      {
        id: "text-1",
        parentId: "root-1",
        domPath: "body>div>p",
        tagName: "P",
        role: "text",
        name: "Body Copy",
        visible: true,
        rect: { x: 60, y: 80, width: 520, height: 96 },
        textContent: "This text is rasterized because the required font is unavailable.",
        fontFamilyCandidates: ["Iowan Old Style", "Times New Roman"],
        resolvedBrowserFontFamily: "Iowan Old Style",
        resolvedBrowserFontStyle: "Roman",
        styles: {
          display: "block",
          position: "static",
          color: "rgb(15, 15, 15)",
          opacity: 1,
          backgroundColor: "rgba(0, 0, 0, 0)",
          backgroundImage: "none",
          borderTopWidth: "0px",
          borderRightWidth: "0px",
          borderBottomWidth: "0px",
          borderLeftWidth: "0px",
          borderTopColor: "rgba(0, 0, 0, 0)",
          borderRightColor: "rgba(0, 0, 0, 0)",
          borderBottomColor: "rgba(0, 0, 0, 0)",
          borderLeftColor: "rgba(0, 0, 0, 0)",
          borderTopLeftRadius: "0px",
          borderTopRightRadius: "0px",
          borderBottomRightRadius: "0px",
          borderBottomLeftRadius: "0px",
          fontFamily: "Iowan Old Style, Times New Roman, serif",
          fontStyle: "normal",
          fontSize: "16px",
          fontWeight: "400",
          lineHeight: "24px",
          letterSpacing: "normal",
          textAlign: "left",
          textTransform: "none",
          objectFit: "fill",
          gridTemplateColumns: "none",
          gridTemplateRows: "none",
          gap: "normal",
          rowGap: "normal",
          columnGap: "normal",
        },
        image: null,
      },
    ],
  });

  assert.throws(
    () =>
      buildCodeToDesignPlan({
        snapshot,
        parentNodeId: "1:2",
        textRasterOverrides: {
          "text-1": {
            dataUrl: "data:image/png;base64,AAAA",
          },
        },
      }),
    /textRasterOverrides are disabled/,
  );
});

test("buildCodeToDesignPlan synthesizes semantic editorial containers for the AItest page", () => {
  const baseStyle = {
    display: "block",
    position: "static",
    color: "rgb(15, 15, 15)",
    opacity: 1,
    backgroundColor: "rgba(0, 0, 0, 0)",
    backgroundImage: "none",
    borderTopWidth: "0px",
    borderRightWidth: "0px",
    borderBottomWidth: "0px",
    borderLeftWidth: "0px",
    borderTopColor: "rgba(0, 0, 0, 0)",
    borderRightColor: "rgba(0, 0, 0, 0)",
    borderBottomColor: "rgba(0, 0, 0, 0)",
    borderLeftColor: "rgba(0, 0, 0, 0)",
    borderTopLeftRadius: "0px",
    borderTopRightRadius: "0px",
    borderBottomRightRadius: "0px",
    borderBottomLeftRadius: "0px",
    fontFamily: "Helvetica Neue, Arial, sans-serif",
    fontStyle: "normal",
    fontSize: "16px",
    fontWeight: "400",
    lineHeight: "24px",
    letterSpacing: "0px",
    textAlign: "left",
    textTransform: "none",
    objectFit: "fill",
    gridTemplateColumns: "none",
    gridTemplateRows: "none",
    gap: "normal",
    rowGap: "normal",
    columnGap: "normal",
    paddingTop: "0px",
    paddingRight: "0px",
    paddingBottom: "0px",
    paddingLeft: "0px",
  };

  const snapshot = buildCodeToDesignRuntimeSnapshot({
    projectRoot: "/tmp/aitest",
    projectName: "aitest",
    route: "/",
    entryPaths: ["src/App.tsx"],
    viewport: {
      width: 1440,
      height: 2200,
      deviceScaleFactor: 1,
    },
    page: {
      title: "Shadow Of Elegance",
      urlPath: "/",
      scrollWidth: 1440,
      scrollHeight: 2200,
      backgroundColor: "rgb(245, 242, 236)",
      backgroundImage: "none",
    },
    nodes: [
      {
        id: "page",
        parentId: null,
        domPath: "body > div.print-editorial-page",
        tagName: "DIV",
        className: "print-editorial-page",
        role: "frame",
        name: "DIV",
        visible: true,
        rect: { x: 0, y: 0, width: 1440, height: 2200 },
        textContent: null,
        styles: { ...baseStyle, backgroundImage: "linear-gradient(rgb(250, 248, 243), rgb(240, 235, 228))" },
        image: null,
      },
      {
        id: "folio",
        parentId: "page",
        domPath: "body > div.print-editorial-page > header.folio-bar",
        tagName: "HEADER",
        className: "folio-bar",
        role: "frame",
        name: "HEADER",
        visible: true,
        rect: { x: 28, y: 0, width: 1384, height: 50 },
        textContent: null,
        styles: { ...baseStyle, display: "grid", columnGap: "12px", gap: "12px", paddingTop: "18px", paddingBottom: "12px", borderBottomWidth: "1px", borderBottomColor: "rgba(15, 15, 15, 0.14)" },
        image: null,
      },
      {
        id: "folio-left",
        parentId: "folio",
        domPath: "span:nth-of-type(1)",
        tagName: "SPAN",
        className: "folio-bar__cell",
        role: "text",
        name: "SPAN",
        visible: true,
        rect: { x: 28, y: 18, width: 453, height: 18 },
        textContent: "No. 124",
        fontFamilyCandidates: ["Helvetica Neue", "Arial"],
        resolvedBrowserFontFamily: "Helvetica Neue",
        resolvedBrowserFontStyle: "Regular",
        styles: { ...baseStyle, fontSize: "11.84px", fontWeight: "400", lineHeight: "18.944px", letterSpacing: "2.1312px", textTransform: "uppercase" },
        image: null,
      },
      {
        id: "folio-center",
        parentId: "folio",
        domPath: "span:nth-of-type(2)",
        tagName: "SPAN",
        className: "folio-bar__cell folio-bar__cell--center",
        role: "text",
        name: "SPAN",
        visible: true,
        rect: { x: 493, y: 18, width: 453, height: 18 },
        textContent: "RUNWAY REVIEW",
        fontFamilyCandidates: ["Helvetica Neue", "Arial"],
        resolvedBrowserFontFamily: "Helvetica Neue",
        resolvedBrowserFontStyle: "Bold",
        styles: { ...baseStyle, fontSize: "11.84px", fontWeight: "700", lineHeight: "18.944px", letterSpacing: "2.1312px", textTransform: "uppercase", textAlign: "center" },
        image: null,
      },
      {
        id: "folio-right",
        parentId: "folio",
        domPath: "span:nth-of-type(3)",
        tagName: "SPAN",
        className: "folio-bar__cell folio-bar__cell--right",
        role: "text",
        name: "SPAN",
        visible: true,
        rect: { x: 958, y: 18, width: 453, height: 18 },
        textContent: "PARIS / ARCHIVE",
        fontFamilyCandidates: ["Helvetica Neue", "Arial"],
        resolvedBrowserFontFamily: "Helvetica Neue",
        resolvedBrowserFontStyle: "Regular",
        styles: { ...baseStyle, fontSize: "11.84px", fontWeight: "400", lineHeight: "18.944px", letterSpacing: "2.1312px", textTransform: "uppercase", textAlign: "right" },
        image: null,
      },
      {
        id: "shell",
        parentId: "page",
        domPath: "main.print-editorial-shell",
        tagName: "MAIN",
        className: "print-editorial-shell",
        role: "frame",
        name: "MAIN",
        visible: true,
        rect: { x: 28, y: 50, width: 1384, height: 2150 },
        textContent: null,
        styles: { ...baseStyle, paddingTop: "26px", paddingBottom: "54px" },
        image: null,
      },
      {
        id: "opening",
        parentId: "shell",
        domPath: "section.opening-spread",
        tagName: "SECTION",
        className: "opening-spread",
        role: "frame",
        name: "SECTION",
        visible: true,
        rect: { x: 28, y: 76, width: 1384, height: 1022 },
        textContent: null,
        styles: { ...baseStyle, display: "grid", columnGap: "24px", gap: "24px" },
        image: null,
      },
      {
        id: "copy",
        parentId: "opening",
        domPath: "div.opening-spread__copy",
        tagName: "DIV",
        className: "opening-spread__copy",
        role: "frame",
        name: "DIV",
        visible: true,
        rect: { x: 28, y: 76, width: 355, height: 759 },
        textContent: null,
        styles: baseStyle,
        image: null,
      },
      {
        id: "kicker",
        parentId: "copy",
        domPath: "p.section-kicker",
        tagName: "P",
        className: "section-kicker",
        role: "text",
        name: "P",
        visible: true,
        rect: { x: 28, y: 76, width: 120, height: 18 },
        textContent: "Fashion Opening",
        fontFamilyCandidates: ["Iowan Old Style", "Times New Roman"],
        resolvedBrowserFontFamily: "Iowan Old Style",
        resolvedBrowserFontStyle: "Bold",
        styles: { ...baseStyle, fontFamily: "Iowan Old Style, Times New Roman, serif", fontSize: "11.84px", fontWeight: "700", lineHeight: "18.944px", letterSpacing: "2.1312px", textTransform: "uppercase" },
        image: null,
      },
      {
        id: "headline",
        parentId: "copy",
        domPath: "h1.spread-headline",
        tagName: "H1",
        className: "spread-headline",
        role: "text",
        name: "H1",
        visible: true,
        rect: { x: 28, y: 108, width: 355, height: 220 },
        textContent: "SHADOW OF ELEGANCE",
        fontFamilyCandidates: ["Didot", "Bodoni 72", "Times New Roman"],
        resolvedBrowserFontFamily: "Didot",
        resolvedBrowserFontStyle: "Semibold",
        styles: { ...baseStyle, fontFamily: "Didot, Bodoni 72, Times New Roman, serif", fontSize: "120px", fontWeight: "600", lineHeight: "100.8px", letterSpacing: "-6px", textTransform: "uppercase" },
        image: null,
      },
      {
        id: "subtitle",
        parentId: "copy",
        domPath: "p.spread-subtitle",
        tagName: "P",
        className: "spread-subtitle",
        role: "text",
        name: "P",
        visible: true,
        rect: { x: 28, y: 346, width: 288, height: 76 },
        textContent: "帽檐、珍珠与黑白之间，复古高定被重新拉回灯下。",
        fontFamilyCandidates: ["Helvetica Neue", "Arial"],
        resolvedBrowserFontFamily: "Helvetica Neue",
        resolvedBrowserFontStyle: "Semibold",
        styles: { ...baseStyle, fontSize: "17.28px", fontWeight: "600", lineHeight: "25.056px" },
        image: null,
      },
      {
        id: "deck",
        parentId: "copy",
        domPath: "p.spread-deck",
        tagName: "P",
        className: "spread-deck",
        role: "text",
        name: "P",
        visible: true,
        rect: { x: 28, y: 444, width: 320, height: 180 },
        textContent: "这组秀场影像并不依赖复杂场景。它只用礼帽、手套、束腰、花饰和波点，把经典时装语言重新压缩成更锋利的轮廓。",
        fontFamilyCandidates: ["Iowan Old Style", "Times New Roman"],
        resolvedBrowserFontFamily: "Iowan Old Style",
        resolvedBrowserFontStyle: "Regular",
        styles: { ...baseStyle, fontFamily: "Iowan Old Style, Times New Roman, serif", fontSize: "15.68px", lineHeight: "27.283px", color: "rgba(15, 15, 15, 0.78)" },
        image: null,
      },
      {
        id: "meta-stack",
        parentId: "copy",
        domPath: "div.spread-meta",
        tagName: "DIV",
        className: "spread-meta",
        role: "frame",
        name: "DIV",
        visible: true,
        rect: { x: 28, y: 652, width: 320, height: 183 },
        textContent: null,
        styles: { ...baseStyle, display: "grid", gap: "16px", paddingTop: "18px", borderTopWidth: "1px", borderTopColor: "rgba(15, 15, 15, 0.12)" },
        image: null,
      },
      {
        id: "meta-item",
        parentId: "meta-stack",
        domPath: "div:nth-of-type(1)",
        tagName: "DIV",
        className: null,
        role: "frame",
        name: "DIV",
        visible: true,
        rect: { x: 28, y: 670, width: 320, height: 34 },
        textContent: null,
        styles: { ...baseStyle, display: "grid", gap: "5px" },
        image: null,
      },
      {
        id: "meta-label",
        parentId: "meta-item",
        domPath: "span.meta-label",
        tagName: "SPAN",
        className: "meta-label",
        role: "text",
        name: "SPAN",
        visible: true,
        rect: { x: 28, y: 670, width: 60, height: 18 },
        textContent: "Story",
        fontFamilyCandidates: ["Iowan Old Style", "Times New Roman"],
        resolvedBrowserFontFamily: "Iowan Old Style",
        resolvedBrowserFontStyle: "Bold",
        styles: { ...baseStyle, fontFamily: "Iowan Old Style, Times New Roman, serif", fontSize: "11.84px", fontWeight: "700", lineHeight: "18.944px", letterSpacing: "2.1312px", textTransform: "uppercase", color: "rgba(15, 15, 15, 0.56)" },
        image: null,
      },
      {
        id: "meta-value",
        parentId: "meta-item",
        domPath: "span.meta-value",
        tagName: "SPAN",
        className: "meta-value",
        role: "text",
        name: "SPAN",
        visible: true,
        rect: { x: 28, y: 693, width: 120, height: 20 },
        textContent: "Haute Codes",
        fontFamilyCandidates: ["Helvetica Neue", "Arial"],
        resolvedBrowserFontFamily: "Helvetica Neue",
        resolvedBrowserFontStyle: "Regular",
        styles: { ...baseStyle, fontSize: "14.72px", lineHeight: "22.08px" },
        image: null,
      },
      {
        id: "hero-figure",
        parentId: "opening",
        domPath: "figure.spread-image--hero",
        tagName: "FIGURE",
        className: "spread-image spread-image--hero",
        role: "frame",
        name: "FIGURE",
        visible: true,
        rect: { x: 407, y: 76, width: 693, height: 1022 },
        textContent: null,
        styles: baseStyle,
        image: null,
      },
      {
        id: "hero-image",
        parentId: "hero-figure",
        domPath: "img",
        tagName: "IMG",
        className: null,
        role: "image",
        name: "IMG",
        visible: true,
        rect: { x: 407, y: 76, width: 693, height: 970 },
        textContent: null,
        styles: { ...baseStyle, objectFit: "cover" },
        image: { src: "/editorial/fashion-7.jpg", alt: "hero", dataUrl: "data:image/png;base64,AAAA" },
      },
      {
        id: "hero-caption",
        parentId: "hero-figure",
        domPath: "figcaption",
        tagName: "FIGCAPTION",
        className: null,
        role: "text",
        name: "FIGCAPTION",
        visible: true,
        rect: { x: 407, y: 1056, width: 384, height: 42 },
        textContent: "A flower at the neckline...",
        fontFamilyCandidates: ["Helvetica Neue", "Arial"],
        resolvedBrowserFontFamily: "Helvetica Neue",
        resolvedBrowserFontStyle: "Regular",
        styles: { ...baseStyle, fontSize: "14.08px", lineHeight: "20.416px", color: "rgba(15, 15, 15, 0.72)" },
        image: null,
      },
      {
        id: "side-rail-source",
        parentId: "opening",
        domPath: "aside.spread-side",
        tagName: "ASIDE",
        className: "spread-side",
        role: "frame",
        name: "ASIDE",
        visible: true,
        rect: { x: 1125, y: 76, width: 287, height: 1022 },
        textContent: null,
        styles: { ...baseStyle, display: "grid", gap: "18px" },
        image: null,
      },
      {
        id: "secondary-figure",
        parentId: "side-rail-source",
        domPath: "figure.spread-image--secondary",
        tagName: "FIGURE",
        className: "spread-image spread-image--secondary",
        role: "frame",
        name: "FIGURE",
        visible: true,
        rect: { x: 1125, y: 76, width: 287, height: 485 },
        textContent: null,
        styles: baseStyle,
        image: null,
      },
      {
        id: "secondary-image",
        parentId: "secondary-figure",
        domPath: "img",
        tagName: "IMG",
        className: null,
        role: "image",
        name: "IMG",
        visible: true,
        rect: { x: 1125, y: 76, width: 287, height: 450 },
        textContent: null,
        styles: { ...baseStyle, objectFit: "cover" },
        image: { src: "/editorial/fashion-5.jpg", alt: "secondary", dataUrl: "data:image/png;base64,BBBB" },
      },
      {
        id: "secondary-caption",
        parentId: "secondary-figure",
        domPath: "figcaption",
        tagName: "FIGCAPTION",
        className: null,
        role: "text",
        name: "FIGCAPTION",
        visible: true,
        rect: { x: 1125, y: 536, width: 287, height: 25 },
        textContent: "Side profile becomes a styling device...",
        fontFamilyCandidates: ["Helvetica Neue", "Arial"],
        resolvedBrowserFontFamily: "Helvetica Neue",
        resolvedBrowserFontStyle: "Regular",
        styles: { ...baseStyle, fontSize: "14.08px", lineHeight: "20.416px", color: "rgba(15, 15, 15, 0.72)" },
        image: null,
      },
      {
        id: "side-note",
        parentId: "side-rail-source",
        domPath: "div.side-note",
        tagName: "DIV",
        className: "side-note",
        role: "frame",
        name: "DIV",
        visible: true,
        rect: { x: 1125, y: 579, width: 287, height: 519 },
        textContent: null,
        styles: { ...baseStyle, paddingTop: "12px", borderTopWidth: "1px", borderTopColor: "rgba(15, 15, 15, 0.12)" },
        image: null,
      },
      {
        id: "side-note-label",
        parentId: "side-note",
        domPath: "p.side-note__label",
        tagName: "P",
        className: "side-note__label",
        role: "text",
        name: "P",
        visible: true,
        rect: { x: 1125, y: 591, width: 100, height: 18 },
        textContent: "Editor's Note",
        fontFamilyCandidates: ["Iowan Old Style", "Times New Roman"],
        resolvedBrowserFontFamily: "Iowan Old Style",
        resolvedBrowserFontStyle: "Bold",
        styles: { ...baseStyle, fontFamily: "Iowan Old Style, Times New Roman, serif", fontSize: "11.84px", fontWeight: "700", lineHeight: "18.944px", letterSpacing: "2.1312px", textTransform: "uppercase", color: "rgba(15, 15, 15, 0.56)" },
        image: null,
      },
      {
        id: "side-note-body",
        parentId: "side-note",
        domPath: "p:nth-of-type(2)",
        tagName: "P",
        className: null,
        role: "text",
        name: "P",
        visible: true,
        rect: { x: 1125, y: 621, width: 287, height: 120 },
        textContent: "纸媒感并不只是加大标题。",
        fontFamilyCandidates: ["Iowan Old Style", "Times New Roman"],
        resolvedBrowserFontFamily: "Iowan Old Style",
        resolvedBrowserFontStyle: "Regular",
        styles: { ...baseStyle, fontFamily: "Iowan Old Style, Times New Roman, serif", fontSize: "15.36px", lineHeight: "25.805px", color: "rgba(15, 15, 15, 0.76)" },
        image: null,
      },
      {
        id: "side-note-page",
        parentId: "side-note",
        domPath: "span.side-note__page",
        tagName: "SPAN",
        className: "side-note__page",
        role: "text",
        name: "SPAN",
        visible: true,
        rect: { x: 1125, y: 765, width: 60, height: 29 },
        textContent: "124",
        fontFamilyCandidates: ["Didot", "Bodoni 72", "Times New Roman"],
        resolvedBrowserFontFamily: "Didot",
        resolvedBrowserFontStyle: "Regular",
        styles: { ...baseStyle, fontFamily: "Didot, Bodoni 72, Times New Roman, serif", fontSize: "28.8px", lineHeight: "28.8px" },
        image: null,
      },
      {
        id: "supporting-block",
        parentId: "shell",
        domPath: "section.supporting-block",
        tagName: "SECTION",
        className: "supporting-block",
        role: "frame",
        name: "SECTION",
        visible: true,
        rect: { x: 28, y: 1132, width: 1384, height: 470 },
        textContent: null,
        styles: { ...baseStyle, display: "grid", columnGap: "22px", gap: "22px", paddingTop: "18px", borderTopWidth: "1px", borderTopColor: "rgba(15, 15, 15, 0.12)" },
        image: null,
      },
      {
        id: "supporting-intro-source",
        parentId: "supporting-block",
        domPath: "div.supporting-block__intro",
        tagName: "DIV",
        className: "supporting-block__intro",
        role: "frame",
        name: "DIV",
        visible: true,
        rect: { x: 28, y: 1150, width: 220, height: 220 },
        textContent: null,
        styles: baseStyle,
        image: null,
      },
      {
        id: "supporting-kicker",
        parentId: "supporting-intro-source",
        domPath: "p.section-kicker",
        tagName: "P",
        className: "section-kicker",
        role: "text",
        name: "P",
        visible: true,
        rect: { x: 28, y: 1150, width: 100, height: 18 },
        textContent: "Detail Study",
        fontFamilyCandidates: ["Iowan Old Style", "Times New Roman"],
        resolvedBrowserFontFamily: "Iowan Old Style",
        resolvedBrowserFontStyle: "Bold",
        styles: { ...baseStyle, fontFamily: "Iowan Old Style, Times New Roman, serif", fontSize: "11.84px", fontWeight: "700", lineHeight: "18.944px", letterSpacing: "2.1312px", textTransform: "uppercase", color: "rgba(15, 15, 15, 0.56)" },
        image: null,
      },
      {
        id: "supporting-heading",
        parentId: "supporting-intro-source",
        domPath: "h2",
        tagName: "H2",
        className: null,
        role: "text",
        name: "H2",
        visible: true,
        rect: { x: 28, y: 1178, width: 160, height: 140 },
        textContent: "High contrast, low excess.",
        fontFamilyCandidates: ["Didot", "Bodoni 72", "Times New Roman"],
        resolvedBrowserFontFamily: "Didot",
        resolvedBrowserFontStyle: "Semibold",
        styles: { ...baseStyle, fontFamily: "Didot, Bodoni 72, Times New Roman, serif", fontSize: "50px", fontWeight: "600", lineHeight: "46px", letterSpacing: "-2.5px" },
        image: null,
      },
      {
        id: "supporting-grid-source",
        parentId: "supporting-block",
        domPath: "div.supporting-grid",
        tagName: "DIV",
        className: "supporting-grid",
        role: "frame",
        name: "DIV",
        visible: true,
        rect: { x: 270, y: 1150, width: 1142, height: 420 },
        textContent: null,
        styles: { ...baseStyle, display: "grid", columnGap: "18px", gap: "18px" },
        image: null,
      },
      {
        id: "supporting-card-1",
        parentId: "supporting-grid-source",
        domPath: "figure.supporting-card:nth-of-type(1)",
        tagName: "FIGURE",
        className: "supporting-card",
        role: "frame",
        name: "FIGURE",
        visible: true,
        rect: { x: 270, y: 1150, width: 350, height: 420 },
        textContent: null,
        styles: { ...baseStyle, display: "grid", gap: "10px" },
        image: null,
      },
      {
        id: "supporting-card-image-1",
        parentId: "supporting-card-1",
        domPath: "img",
        tagName: "IMG",
        className: null,
        role: "image",
        name: "IMG",
        visible: true,
        rect: { x: 270, y: 1150, width: 350, height: 360 },
        textContent: null,
        styles: { ...baseStyle, objectFit: "cover" },
        image: { src: "/editorial/fashion-2.jpg", alt: "pearls", dataUrl: "data:image/png;base64,CCCC" },
      },
      {
        id: "supporting-card-label-1",
        parentId: "supporting-card-1",
        domPath: "span",
        tagName: "SPAN",
        className: null,
        role: "text",
        name: "SPAN",
        visible: true,
        rect: { x: 270, y: 1520, width: 80, height: 18 },
        textContent: "Pearls",
        fontFamilyCandidates: ["Iowan Old Style", "Times New Roman"],
        resolvedBrowserFontFamily: "Iowan Old Style",
        resolvedBrowserFontStyle: "Bold",
        styles: { ...baseStyle, fontFamily: "Iowan Old Style, Times New Roman, serif", fontSize: "11.84px", fontWeight: "700", lineHeight: "18.944px", letterSpacing: "2.1312px", textTransform: "uppercase" },
        image: null,
      },
      {
        id: "supporting-card-note-1",
        parentId: "supporting-card-1",
        domPath: "p",
        tagName: "P",
        className: null,
        role: "text",
        name: "P",
        visible: true,
        rect: { x: 270, y: 1546, width: 350, height: 44 },
        textContent: "Long strands and a sharply cut jacket turn adornment into structure.",
        fontFamilyCandidates: ["Iowan Old Style", "Times New Roman"],
        resolvedBrowserFontFamily: "Iowan Old Style",
        resolvedBrowserFontStyle: "Regular",
        styles: { ...baseStyle, fontFamily: "Iowan Old Style, Times New Roman, serif", fontSize: "14.4px", lineHeight: "22.32px", color: "rgba(15, 15, 15, 0.72)" },
        image: null,
      },
      {
        id: "look-rail-source",
        parentId: "shell",
        domPath: "section.look-rail",
        tagName: "SECTION",
        className: "look-rail",
        role: "frame",
        name: "SECTION",
        visible: true,
        rect: { x: 28, y: 1636, width: 1384, height: 514 },
        textContent: null,
        styles: { ...baseStyle, display: "grid", columnGap: "22px", gap: "22px", paddingTop: "18px", borderTopWidth: "1px", borderTopColor: "rgba(15, 15, 15, 0.12)" },
        image: null,
      },
      {
        id: "look-rail-intro-source",
        parentId: "look-rail-source",
        domPath: "div.look-rail__intro",
        tagName: "DIV",
        className: "look-rail__intro",
        role: "frame",
        name: "DIV",
        visible: true,
        rect: { x: 28, y: 1654, width: 330, height: 200 },
        textContent: null,
        styles: baseStyle,
        image: null,
      },
      {
        id: "look-rail-kicker",
        parentId: "look-rail-intro-source",
        domPath: "p.section-kicker",
        tagName: "P",
        className: "section-kicker",
        role: "text",
        name: "P",
        visible: true,
        rect: { x: 28, y: 1654, width: 120, height: 18 },
        textContent: "Selected Looks",
        fontFamilyCandidates: ["Iowan Old Style", "Times New Roman"],
        resolvedBrowserFontFamily: "Iowan Old Style",
        resolvedBrowserFontStyle: "Bold",
        styles: { ...baseStyle, fontFamily: "Iowan Old Style, Times New Roman, serif", fontSize: "11.84px", fontWeight: "700", lineHeight: "18.944px", letterSpacing: "2.1312px", textTransform: "uppercase", color: "rgba(15, 15, 15, 0.56)" },
        image: null,
      },
      {
        id: "look-rail-body",
        parentId: "look-rail-intro-source",
        domPath: "p:nth-of-type(2)",
        tagName: "P",
        className: null,
        role: "text",
        name: "P",
        visible: true,
        rect: { x: 28, y: 1684, width: 288, height: 76 },
        textContent: "收腰、花饰、柔粉与短外套让这一组造型保留经典时装的完整礼仪。",
        fontFamilyCandidates: ["Iowan Old Style", "Times New Roman"],
        resolvedBrowserFontFamily: "Iowan Old Style",
        resolvedBrowserFontStyle: "Regular",
        styles: { ...baseStyle, fontFamily: "Iowan Old Style, Times New Roman, serif", fontSize: "15.2px", lineHeight: "25.536px", color: "rgba(15, 15, 15, 0.74)" },
        image: null,
      },
      {
        id: "look-rail-images-source",
        parentId: "look-rail-source",
        domPath: "div.look-rail__images",
        tagName: "DIV",
        className: "look-rail__images",
        role: "frame",
        name: "DIV",
        visible: true,
        rect: { x: 380, y: 1654, width: 1032, height: 496 },
        textContent: null,
        styles: { ...baseStyle, display: "grid", columnGap: "18px", gap: "18px" },
        image: null,
      },
      {
        id: "rail-figure-1",
        parentId: "look-rail-images-source",
        domPath: "figure.rail-image:nth-of-type(1)",
        tagName: "FIGURE",
        className: "rail-image",
        role: "frame",
        name: "FIGURE",
        visible: true,
        rect: { x: 380, y: 1654, width: 332, height: 496 },
        textContent: null,
        styles: baseStyle,
        image: null,
      },
      {
        id: "rail-image-1",
        parentId: "rail-figure-1",
        domPath: "img",
        tagName: "IMG",
        className: null,
        role: "image",
        name: "IMG",
        visible: true,
        rect: { x: 380, y: 1654, width: 332, height: 496 },
        textContent: null,
        styles: { ...baseStyle, objectFit: "cover" },
        image: { src: "/editorial/fashion-1.jpg", alt: "rail-1", dataUrl: "data:image/png;base64,DDDD" },
      },
    ],
  });

  const plan = buildCodeToDesignPlan({
    snapshot,
    parentNodeId: "1:2",
  });

  const layoutNames = JSON.stringify(plan.layoutTree);
  assert.match(layoutNames, /"Folio Bar"/);
  assert.match(layoutNames, /"Opening Spread"/);
  assert.match(layoutNames, /"Supporting Grid"/);
  assert.match(layoutNames, /"Look Rail Images"/);
  assert.equal(plan.qualityReport.structure.status, "pass");
  assert.equal(plan.qualityReport.naming.status, "pass");
  assert.equal(plan.qualityReport.fontAlignment.status, "pending");
  assert.equal(
    findNodeById(plan.layoutTree, "opening-spread")?.layout?.layoutWrap,
    "WRAP",
  );
  assert.equal(
    findNodeById(plan.layoutTree, "supporting-grid")?.layout?.layoutWrap,
    "WRAP",
  );
  assert.equal(
    findNodeById(plan.layoutTree, "look-rail-images")?.layout?.layoutWrap,
    "WRAP",
  );
  assert.equal(plan.batch.commands.some((command) => command.type === "capability" && command.capabilityId === "layout.configure-frame"), true);
  assert.equal(plan.batch.commands.some((command) => command.type === "capability" && command.capabilityId === "nodes.create-line"), true);
  const capabilityCommands = plan.batch.commands.filter((command) => command.type === "capability");

  const folioDividerCreate = capabilityCommands.find((command) =>
    command.capabilityId === "nodes.create-line" &&
    (command.payload as { analysisRefId?: string }).analysisRefId === "code-to-design:layout:folio-bar-bottom-divider",
  );
  assert.ok(folioDividerCreate);
  assert.equal((folioDividerCreate.payload as { x?: number }).x, 0);
  assert.equal((folioDividerCreate.payload as { y?: number }).y, 49);

  const folioDividerAbsolute = capabilityCommands.find((command) =>
    command.capabilityId === "layout.configure-child" &&
    (command.nodeIds || []).includes("analysis:code-to-design:layout:folio-bar-bottom-divider"),
  );
  assert.ok(folioDividerAbsolute);

  const folioDividerPosition = capabilityCommands.find((command) =>
    command.capabilityId === "geometry.set-position" &&
    (command.nodeIds || []).includes("analysis:code-to-design:layout:folio-bar-bottom-divider"),
  );
  assert.ok(folioDividerPosition);
  assert.deepEqual(folioDividerPosition.payload, { x: 0, y: 49 });

  const supportingDividerPosition = capabilityCommands.find((command) =>
    command.capabilityId === "geometry.set-position" &&
    (command.nodeIds || []).includes("analysis:code-to-design:layout:supporting-block-top-divider"),
  );
  assert.ok(supportingDividerPosition);
  assert.deepEqual(supportingDividerPosition.payload, { x: 0, y: 0 });

  const lookRailDividerPosition = capabilityCommands.find((command) =>
    command.capabilityId === "geometry.set-position" &&
    (command.nodeIds || []).includes("analysis:code-to-design:layout:look-rail-top-divider"),
  );
  assert.ok(lookRailDividerPosition);
  assert.deepEqual(lookRailDividerPosition.payload, { x: 0, y: 0 });

  const folioBarSize = capabilityCommands.find((command) =>
    command.capabilityId === "geometry.set-size" &&
    (command.nodeIds || []).includes("analysis:code-to-design:layout:folio-bar"),
  );
  assert.ok(folioBarSize);
  assert.deepEqual(folioBarSize.payload, { width: 1384, height: 50 });

  const supportingBlockSize = capabilityCommands.find((command) =>
    command.capabilityId === "geometry.set-size" &&
    (command.nodeIds || []).includes("analysis:code-to-design:layout:supporting-block"),
  );
  assert.ok(supportingBlockSize);

  const lookRailSize = capabilityCommands.find((command) =>
    command.capabilityId === "geometry.set-size" &&
    (command.nodeIds || []).includes("analysis:code-to-design:layout:look-rail"),
  );
  assert.ok(lookRailSize);
});
