import type { ProjectData } from "./types.js";

export const seededProject: ProjectData = {
  meta: {
    id: "figmatest-main",
    name: "Figmatest Workspace",
    description:
      "用于验证 Figma 设计信息、React 原型映射和 Runtime AI 上下文是否能对齐的本地工作台。",
    updatedAt: "2026-03-22T00:00:00.000Z",
  },
  designSources: [
    {
      id: "source-mobile-banking",
      name: "Mobile Banking App",
      figmaFileKey: "FigmaKey-Banking-App",
      branch: "main",
      status: "connected",
      lastSyncedAt: "2026-03-22T00:00:00.000Z",
      summary: "主文件包含 onboarding、dashboard 与 transfer 流程，适合做状态映射测试。",
    },
    {
      id: "source-design-system",
      name: "Design System Foundations",
      figmaFileKey: "FigmaKey-Design-System",
      branch: "tokens",
      status: "draft",
      lastSyncedAt: "2026-03-21T16:30:00.000Z",
      summary: "记录颜色、间距、按钮和输入框变体，为 React 组件库做命名对齐。",
    },
  ],
  designScreens: [
    {
      id: "screen-onboarding",
      sourceId: "source-mobile-banking",
      name: "Onboarding / Welcome",
      purpose: "验证欢迎页的层级、引导卡片与 CTA 状态。",
      stateNotes: ["default", "loading", "error-inline"],
      summary: "首屏强调信息密度控制和 CTA 对齐，是连调入口页。",
    },
    {
      id: "screen-dashboard",
      sourceId: "source-mobile-banking",
      name: "Dashboard / Account Overview",
      purpose: "验证卡片编排、余额显隐和快捷操作状态。",
      stateNotes: ["default", "skeleton", "empty"],
      summary: "包含信息卡片、活动列表与快捷入口，适合做组件复用测试。",
    },
    {
      id: "screen-button-system",
      sourceId: "source-design-system",
      name: "Buttons / States",
      purpose: "整理主按钮、次按钮和危险按钮的交互状态。",
      stateNotes: ["default", "hover", "disabled", "loading"],
      summary: "为按钮组件定义状态矩阵和 token 使用边界。",
    },
  ],
  componentMappings: [
    {
      id: "mapping-hero-card",
      designName: "Welcome Hero Card",
      reactName: "HeroIntroCard",
      status: "prototype",
      props: ["title", "description", "ctaLabel", "onCtaClick"],
      states: ["default", "loading"],
      notes: "设计稿里 CTA 的次级说明需要保留为可选 props，避免写死。",
      screenIds: ["screen-onboarding"],
    },
    {
      id: "mapping-account-tile",
      designName: "Account Overview Tile",
      reactName: "AccountOverviewTile",
      status: "planned",
      props: ["accountName", "balance", "trend", "masked"],
      states: ["default", "skeleton", "empty"],
      notes: "余额显隐逻辑要和设计上的 masked 状态保持一致。",
      screenIds: ["screen-dashboard"],
    },
    {
      id: "mapping-button-primary",
      designName: "Button / Primary",
      reactName: "PrimaryButton",
      status: "verified",
      props: ["children", "disabled", "loading", "icon"],
      states: ["default", "hover", "disabled", "loading"],
      notes: "按钮尺寸与 loading icon 对齐是当前最稳定的一条映射。",
      screenIds: ["screen-button-system", "screen-onboarding"],
    },
  ],
  reviewItems: [
    {
      id: "review-copy-tone",
      title: "欢迎页文案层级是否与实现组件树一致",
      area: "design",
      status: "doing",
      owner: "Product + Frontend",
      detail: "当前文案分组在设计上分成三层，但 React 原型只预留了两层文本槽位。",
      relatedIds: ["screen-onboarding", "mapping-hero-card"],
    },
    {
      id: "review-balance-mask",
      title: "余额显隐交互在 skeleton 状态下的展示规则",
      area: "prototype",
      status: "todo",
      owner: "Frontend",
      detail: "需要确认 loading 时仍显示占位骨架，不能直接暴露真实数值。",
      relatedIds: ["screen-dashboard", "mapping-account-tile"],
    },
    {
      id: "review-runtime-context",
      title: "Runtime Context Pack 是否覆盖设计来源和组件状态",
      area: "runtime",
      status: "todo",
      owner: "AI",
      detail: "后续接 Figma MCP 时，需要确认上下文中能带上 file key、screen 和 component mapping。",
      relatedIds: ["source-mobile-banking", "mapping-button-primary"],
    },
  ],
  runtimeSessions: [
    {
      id: "session-summary-1",
      graphKind: "codegraph",
      action: "codegraph/summarize",
      selectionIds: ["screen-dashboard", "mapping-account-tile"],
      updatedAt: "2026-03-22T00:00:00.000Z",
      lastResultSummary: "对 Dashboard 和 AccountOverviewTile 做联合摘要，适合作为联调起点。",
    },
  ],
};
